import { ScreenMode } from '@/context/context'
import React, { useContext } from 'react'
import Header from './Header'
import Sidebar from './Sidebar'
import Head from 'next/head'

const Layout = ({children}) => {
  const {dark} = useContext(ScreenMode)
  return (
    <>
      <Head>
        <title>Abodes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    <div className={`flex ${dark? 'text-white': ''}`}>
        <Sidebar />
        <div className='w-full'>
          <Header />
          <div className= {` ${dark? 'bg-secondarydark': 'bg-gray-100'} min-h-[100vh] p-[2.5%] sm:p-[20px]`}>
            {children}
          </div>
        </div>
    </div>
    </>
  )
}

export default Layout