import React from 'react'
import Header from './Header'
import Sidebar from './Sidebar'
import Head from 'next/head'

const Layout = ({children}) => {
  return (
    <>
      <Head>
        <title>Abodes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    <div className='flex'>
        <Sidebar />
        <div className='w-full'>
          <Header />
          <div className='bg-gray-100 p-[20px]'>
            {children}
          </div>
        </div>
    </div>
    </>
  )
}

export default Layout