import Head from 'next/head'
import { Inter } from 'next/font/google'
import PieCard from '@/components/PieCard'
import TotalRevenue from '@/components/TotalRevenue'
import PropertyReferrals from '@/components/PropertyReferrals'
import PropertyList from '@/components/PropertyList'
import TopAgent from '@/components/TopAgent'
import Customer from '@/components/Customer'
import LatestSales from '@/components/LatestSales'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  
  return (
    <>
      <Head>
        <title>Abodes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <h1 className='text-[25px] font-bold'>Dashboard</h1>
        <div className='flex flex-wrap justify-between gap-[20px]'>
          <PieCard 
            title="Properties for Sale"
            value="684"
            series={[30, 70]}
            colors={['#E4E8EF', '#475BE8']}
          />
          <PieCard 
            title="Properties for Rent"
            value="764"
            series={[60, 40]}
            colors={['#E4E8EF', '#FD8539']}
          />
          <PieCard 
            title="Total Customers"
            value="1284"
            series={[45, 55]}
            colors={['#E4E8EF', '#2ED480']}
          />
          <PieCard 
            title="Total City"
            value="90"
            series={[45, 55]}
            colors={['#E4E8EF', '#FE6D8E']}
          />
        </div>

        <div className='mt-[20px] flex gap-[20px] flex-col md:flex-row'>
          <TotalRevenue />
          <PropertyReferrals />
        </div>
        <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-[20px] mt-[20px]'>
          <TopAgent />
          <Customer />
          <LatestSales />
        </div>
        <PropertyList />
      </main>
    </>
  )
}
